### ISSUE TITLE
how to change the input to gray images?

### ISSUE THREAD

**Issue by yongshuo-Z** [anonymoussss/IDRiD_sub1_EX#3]
Hello! I want to change the training input to gray images, and I have put the images in the correct directory. I change line 195 in unet.py from: 
image = tf.placeholder(tf.int32,[None,IMG_SIZE,IMG_SIZE, 3], name='image') 
to:
image = tf.placeholder(tf.int32,[None,IMG_SIZE,IMG_SIZE, 1], name='image') 
Then I got the error:
######################################################################
Traceback (most recent call last):
  File "unet.py", line 344, in <module>
    tf.app.run()
  File "/home/ilab/anaconda3/envs/seg36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "unet.py", line 246, in main
    tra_positive_prob, train_err, _ = sess.run([train_positive_prob, train_loss_op,train_op], feed_dict=feed_dict)
  File "/home/ilab/anaconda3/envs/seg36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/ilab/anaconda3/envs/seg36/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (3, 512, 512) for Tensor 'Cast:0', which has shape '(?, 512, 512, 1)'
#####################################################################
I have been stuck here for days and don't know what is wrong. Thanks in advance for your help!!

**Comment by anonymoussss** [comment]
The data reader code is written in BatchDatasetReader.py >> def _transform. You can change it in your way.
